### PR TITLE
move ribbon to left

### PR DESCRIPTION
**Pull request by xcodebuild**
move ribbon to left,or it will block the run button

### CODE REVIEW

**Comment by tiye** [comment]
Nice but I don't think it's good way to use `rotate()`.
For the ribbon you may check this: https://github.com/blog/273-github-ribbons
And I added one here in case you need it: http://coffee-js.qiniudn.com/ribbon-left.png

I did some test but not find `run` button was covered os something, can you add some details like picture?

Also don't contain changes of `index.html` in your commit, since it's generated. Just leave it to me, I will compile it before pushing to the server.

**Comment by xcodebuild** [comment]
covered

Archlinux Chromium  35.0.1916.153 (274914)

**Comment by tiye** [comment]
Looks we would have another problem putting it on the left... got other ideas?
coffee

**Comment by xcodebuild** [comment]
A better way to slove this problem.See #12

**Pull request closed without merging**
